export const aliasMap = new Map()

aliasMap.set('Necrozma-Dusk-Mane', 'Necrozma-DM');
aliasMap.set('Necrozma-Dawn-Wings', 'Necrozma-DW');
aliasMap.set('Calyrex-Shadow', 'Calyrex-S');
aliasMap.set('Calyrex-Ice', 'Calyrex-I');
aliasMap.set('Giratina-Origin', 'Giratina-O');
aliasMap.set('Kyurem-Black', 'Kyurem-B');
aliasMap.set('Kyurem-White', 'Kyurem-W');
aliasMap.set('Tornadus-Therian', 'Tornadus-T');
aliasMap.set('Landorus-Therian', 'Landorus-T');
aliasMap.set('Thundurus-Therian', 'Thundurus-T');
aliasMap.set('Zamazenta-Crowned', 'Zamazenta-C');
aliasMap.set('Zacian-Crowned', 'Zacian-C');
aliasMap.set('Darmanitan-Galar', 'Galarian Darmanitan');
aliasMap.set('Slowking-Galar', 'Galarian Slowking');
aliasMap.set('Slowbro-Galar', 'Galarian Slowbro');
aliasMap.set('Weezing-Galar', 'Galarian Weezing');
aliasMap.set('Meowth-Galar', 'Galarian Meowth');
aliasMap.set('Ponyta-Galar', 'Galarian Ponyta');
aliasMap.set('Rapidash-Galar', 'Galarian Rapidash');
aliasMap.set('Slowpoke-Galar', 'Galarian Slowpoke');
aliasMap.set('Farfetch\'d-Galar', 'Galarian Farfetch\'d');
aliasMap.set('Mr. Mime-Galar', 'Galarian Mr. Mime');
aliasMap.set('Articuno-Galar', 'Galarian Articuno');
aliasMap.set('Moltres-Galar', 'Galarian Moltres');
aliasMap.set('Zapdos-Galar', 'Galarian Zapdos');
aliasMap.set('Corsola-Galar', 'Galarian Corsola');
aliasMap.set('Zigzagoon-Galar', 'Galarian Zigzagoon');
aliasMap.set('Linoone-Galar', 'Galarian Linoone');
aliasMap.set('Darumaka-Galar', 'Galarian Darumaka');
aliasMap.set('Yamask-Galar', 'Galarian Yamask');
aliasMap.set('Stunfisk-Galar', 'Galarian Stunfisk');